-- ============================================================
-- INCREMENTAL V4 - HARDWARE INDUSTRIAL / DEEPTECH / VC-GRADE
-- ------------------------------------------------------------
-- Cette migration ajoute :
--   1. Nouvelles colonnes pour matching plus fin :
--      - asset_class (software_pure / software_with_hardware /
--        hardware_industrial / deep_tech_research / etc.)
--      - vc_relevance_score (1-5, sert de boost de tri)
--      - capital_intensity (low / medium / high / very high)
--      - vertical_v4 (label de vertical detaillee)
--      - source_2, what_made_it_work, key_risks_lessons
--   2. Backfill des 129 lignes V3 sur asset_class + vc_relevance_score
--      par regle deterministe basee sur leur secteur.
--   3. Suppression des doublons V3 (Anduril, Helsing, Shield AI, etc.)
--      qui sont mieux documentes dans V4.
--   4. Insertion des 56 lignes V4 hardware/industrial/deeptech.
--   5. Insertion d ajouts personnels : Pasqal (chiffres frais 2026),
--      Atom Computing, PsiQuantum, Sila Nanotechnologies, QuantumScape,
--      Boom Supersonic, Relativity Space, Sierra Space, Carbon Inc.,
--      Apptronik, 1X Technologies, Sanctuary AI, Symbotic.
--
-- ============================================================

-- 1. Ajout colonnes (idempotent)
alter table public.historical_companies add column if not exists asset_class text;
alter table public.historical_companies add column if not exists vc_relevance_score integer;
alter table public.historical_companies add column if not exists capital_intensity text;
alter table public.historical_companies add column if not exists vertical_v4 text;
alter table public.historical_companies add column if not exists source_2 text;
alter table public.historical_companies add column if not exists what_made_it_work text;
alter table public.historical_companies add column if not exists key_risks_lessons text;

-- 2. Backfill asset_class sur V3 par regle deterministe.
-- Software pur : SaaS, AI, Marketplace, Consumer, Fintech (les Adyen,
-- Spotify, Mistral, OpenAI, Anthropic, Cohere, etc.)
update public.historical_companies set asset_class = 'software_pure'
  where asset_class is null
  and (sector ilike 'AI%' or sector ilike 'SaaS%' or sector ilike 'Fintech%'
       or sector ilike 'E-commerce%' or sector ilike 'Marketplace%'
       or sector ilike 'Consumer%' or sector ilike 'Cybersecurity%'
       or sector ilike 'Gaming%' or sector ilike 'Crypto%' or sector = 'Cloud'
       or sector ilike 'Insurtech%' or sector ilike 'Healthtech%'
       or sector ilike 'Foodtech%');
-- Hardware industrial / deeptech : Quantum, IoT, Mobility (hors digital)
update public.historical_companies set asset_class = 'hardware_industrial'
  where asset_class is null
  and (sector ilike 'Mobility%' or sector ilike 'Greentech%' or sector ilike 'IoT%');
update public.historical_companies set asset_class = 'deep_tech_research'
  where asset_class is null and sector = 'Quantum';
-- Fallback : tout le reste en software_pure
update public.historical_companies set asset_class = 'software_pure'
  where asset_class is null;

-- 3. Backfill vc_relevance_score V3 par defaut a 3
update public.historical_companies set vc_relevance_score = 3
  where vc_relevance_score is null;

-- 4. Suppression doublons V3 qui seront mieux documentes en V4
delete from public.historical_companies where name in (
  'Anduril',
  'Helsing',
  'Shield AI',
  'Skydio',
  'Tekever',
  'Quantum Systems',
  'Wayve',
  'Saildrone',
  'Northvolt',
  'Form Energy',
  'IonQ',
  'PsiQuantum');

-- 5. Insertion V4 - 56 lignes hardware/industrial/deeptech
insert into public.historical_companies
  (name, country, sector, sub_sector, subsector, founded, outcome, exit_type,
   region, eu_status, state_influence_tag, data_quality, primary_source_url,
   analyst_note, confidence_score,
   asset_class, vc_relevance_score, capital_intensity, vertical_v4,
   source_2, what_made_it_work, key_risks_lessons)
values
  ('Anduril Industries', 'USA', 'Drones / Defense tech', 'autonomous defense systems', 'autonomous defense systems', null, 'success_private', 'hypergrowth private', 'NorthAmerica', null, null, 'medium-high', 'https://www.axios.com/2026/03/04/anduril-palmer-luckey-valuation', 'Defense procurement timing, software-defined hardware, founder-market fit, rapid productization, DoD demand for autonomy.', 4, 'hardware_industrial', 5, 'high', 'Drones / Defense tech', 'https://www.reuters.com/business/aerospace-defense/', 'Defense procurement timing, software-defined hardware, founder-market fit, rapid productization, DoD demand for autonomy.', 'Regulatory/procurement dependency; massive manufacturing execution risk.'),
  ('Shield AI', 'USA', 'Drones / Defense tech', 'AI pilot / autonomous aircraft', 'AI pilot / autonomous aircraft', null, 'success_private', 'hypergrowth private', 'NorthAmerica', null, null, 'high', 'https://shield.ai/shield-ai-to-acquire-software-simulation-company-aechelon-and-raise-2b-at-12-7b-valuation/', 'Clear military need: autonomy in GPS-denied environments; product platform Hivemind; expansion by acquisition.', 4, 'hardware_industrial', 5, 'high', 'Drones / Defense tech', 'https://www.reuters.com/business/aerospace-defense/defense-technology-startup-shield-ai-valued-127-billion-latest-funding-round-2026-03-26/', 'Clear military need: autonomy in GPS-denied environments; product platform Hivemind; expansion by acquisition.', 'Defense-cycle dependence; battlefield claims need technical validation.'),
  ('Skydio', 'USA', 'Drones / Defense tech', 'autonomous drones / inspection / public safety', 'autonomous drones / inspection / public safety', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'high', 'https://www.skydio.com/blog/skydio-raises-230-million-series-e-funding-round', 'Autonomous flight software, US-made drone positioning, demand from enterprise/public sector/critical infrastructure.', 4, 'hardware_industrial', 5, 'medium-high', 'Drones / Defense tech', 'https://techcrunch.com/2023/02/27/skydio-soars-to-a-2-2-billion-valuation-after-raising-230m-series-e/', 'Autonomous flight software, US-made drone positioning, demand from enterprise/public sector/critical infrastructure.', 'Hardware manufacturing and procurement concentration; DJI/global competition.'),
  ('Zipline', 'USA', 'Drones / Logistics', 'drone delivery logistics', 'drone delivery logistics', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'medium-high', 'https://www.bloomberg.com/news/articles/2026-01-20/drone-delivery-startup-zipline-hits-7-6-billion-valuation', 'Clear mission-critical use cases, operational density, real-world delivery volume, vertical integration.', 4, 'hardware_industrial', 5, 'high', 'Drones / Logistics', 'https://www.flyzipline.com/', 'Clear mission-critical use cases, operational density, real-world delivery volume, vertical integration.', 'Regulatory permissions, route economics, hardware operations complexity.'),
  ('Helsing', 'Germany', 'Defense AI / autonomous systems', 'defense AI, drones, autonomy', 'defense AI, drones, autonomy', null, 'success_private', 'hypergrowth private', 'Europe', null, null, 'high', 'https://helsing.ai/newsroom/helsing-raises-eur600m-to-invest-in-european-technological-sovereignty', 'European defense sovereignty tailwind, AI software core, government demand after Ukraine war, strong investor syndicate.', 4, 'hardware_industrial', 5, 'medium-high', 'Defense AI / autonomous systems', 'https://www.reuters.com/business/aerospace-defense/german-defence-start-up-helsing-raises-600-million-euros-latest-investment-round-2025-06-17/', 'European defense sovereignty tailwind, AI software core, government demand after Ukraine war, strong investor syndicate.', 'State budget cycles, dual-use ethics, export controls.'),
  ('Quantum Systems', 'Germany', 'Drones / Dual-use', 'aerial intelligence drones', 'aerial intelligence drones', null, 'active', 'private scale-up', 'Europe', null, null, 'high', 'https://quantum-systems.com/news/quantum-systems-raises-euro160m/', 'Dual-use drone demand, Ukraine/NATO tailwind, autonomous systems and production scale-up.', 4, 'hardware_industrial', 5, 'medium-high', 'Drones / Dual-use', 'https://quantum-systems.com/news/quantum-systems-triples-valuation/', 'Dual-use drone demand, Ukraine/NATO tailwind, autonomous systems and production scale-up.', 'Defense procurement concentration; valuation sensitive to geopolitical cycle.'),
  ('Epirus', 'USA', 'Counter-drone / Defense hardware', 'directed energy anti-drone systems', 'directed energy anti-drone systems', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'high', 'https://www.epirusinc.com/press-releases/epirus-raises-200-million-in-series-c-funding', 'Counter-UAS demand, distinctive directed-energy product, government contract pull.', 4, 'hardware_industrial', 5, 'high', 'Counter-drone / Defense hardware', 'https://www.reuters.com/business/aerospace-defense/defense-tech-startup-epirus-secures-250-million-make-anti-drone-weapons-2025-03-05/', 'Counter-UAS demand, distinctive directed-energy product, government contract pull.', 'Long defense sales cycles; technical validation and deployment constraints.'),
  ('Red Cat / Teal Drones', 'USA', 'Drones / Defense tech', 'small drones for defense/public safety', 'small drones for defense/public safety', null, 'medium', 'public small-cap / acquisition roll-up', 'NorthAmerica', null, null, 'high', 'https://ir.redcatholdings.com/news-events/press-releases/detail/37/red-cat-holdings-closes-acquisition-of-teal-drones', 'Buy-and-build around defense-compliant drone manufacturing; US procurement tailwind.', 3, 'hardware_industrial', 4, 'medium', 'Drones / Defense tech', 'https://ir.redcatholdings.com/news-events/press-releases/detail/29/red-cat-holdings-to-acquire-teal-drones', 'Buy-and-build around defense-compliant drone manufacturing; US procurement tailwind.', 'Small-cap volatility; execution depends on contracts and product reliability.'),
  ('Saildrone', 'USA', 'Autonomous maritime drones', 'uncrewed surface vehicles / ocean data', 'uncrewed surface vehicles / ocean data', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'medium', 'https://research.contrary.com/company/saildrone', 'Differentiated autonomous maritime platform, defense/climate/ocean data use cases, recurring data value.', 3, 'hardware_industrial', 4, 'medium-high', 'Autonomous maritime drones', 'https://www.saildrone.com/', 'Differentiated autonomous maritime platform, defense/climate/ocean data use cases, recurring data value.', 'Hardware deployment, maintenance at sea, government/commercial sales mix.'),
  ('TEKEVER', 'Portugal / UK', 'Drones / Maritime surveillance', 'AI-driven UAVs for civil and defense missions', 'AI-driven UAVs for civil and defense missions', null, 'active', 'private scale-up', 'Europe', null, null, 'medium', 'https://www.tekever.com/', 'Clear niche in long-range maritime surveillance, European defense/civil contracts, AI autonomy positioning.', 3, 'hardware_industrial', 4, 'medium-high', 'Drones / Maritime surveillance', 'https://en.wikipedia.org/wiki/Tekever', 'Clear niche in long-range maritime surveillance, European defense/civil contracts, AI autonomy positioning.', 'Funding/outcome data less transparent; require manual diligence.'),
  ('Figure AI', 'USA', 'Robotics / Humanoid', 'general-purpose humanoid robots', 'general-purpose humanoid robots', null, 'success_private', 'hypergrowth private', 'NorthAmerica', null, null, 'high', 'https://www.figure.ai/news/series-c', 'Founder pedigree, humanoid robotics hype cycle, major strategic investors, manufacturing ambition.', 4, 'hardware_industrial', 5, 'high', 'Robotics / Humanoid', 'https://www.reuters.com/business/figure-valued-39-billion-latest-funding-round-2025-09-16/', 'Founder pedigree, humanoid robotics hype cycle, major strategic investors, manufacturing ambition.', 'Extreme valuation risk; commercialization proof still central.'),
  ('Agility Robotics', 'USA', 'Robotics / Humanoid logistics', 'bipedal robots for warehouses', 'bipedal robots for warehouses', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'high', 'https://www.agilityrobotics.com/content/agility-robotics-raises-150m-series-b-led-by-dcvc-and-playground-global', 'Focused warehouse/labor use case, Digit platform, logistics automation demand.', 3, 'hardware_industrial', 4, 'high', 'Robotics / Humanoid logistics', 'https://www.agilityrobotics.com/', 'Focused warehouse/labor use case, Digit platform, logistics automation demand.', 'Humanoid ROI must beat simpler warehouse robots; manufacturing scale risk.'),
  ('Locus Robotics', 'USA', 'Warehouse robotics', 'autonomous mobile robots', 'autonomous mobile robots', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'high', 'https://www.prnewswire.com/news-releases/locus-robotics-announces-117-million-in-series-f-funding-bringing-its-valuation-close-to-2-billion-301688564.html', 'Clear ROI in fulfillment, RaaS/business model flexibility, large retail/logistics demand.', 4, 'hardware_industrial', 5, 'medium-high', 'Warehouse robotics', 'https://research.contrary.com/company/locus-robotics', 'Clear ROI in fulfillment, RaaS/business model flexibility, large retail/logistics demand.', 'Warehouse capex cycles; integration into existing workflows.'),
  ('Covariant', 'USA', 'Robotics AI', 'robotic foundation models / warehouse picking', 'robotic foundation models / warehouse picking', null, 'medium', 'strategic licensing / talent acquisition', 'NorthAmerica', null, null, 'high', 'https://www.aboutamazon.com/news/company-news/amazon-covariant-ai-robots', 'World-class AI/robotics team, narrow high-value warehouse automation problem, foundation-model narrative.', 3, 'hardware_industrial', 4, 'medium', 'Robotics AI', 'https://techcrunch.com/2024/08/31/amazon-hires-the-founders-of-robotics-ai-startup-covariant/', 'World-class AI/robotics team, narrow high-value warehouse automation problem, foundation-model narrative.', 'Acqui-hire/licensing outcome may not equal full investor win; verify cap table outcome.'),
  ('Exotec', 'France', 'Industrial robotics', 'warehouse robotics systems', 'warehouse robotics systems', null, 'success_private', 'private unicorn', 'Europe', null, null, 'high', 'https://www.exotec.com/news/robotics-pioneer-exotec-raises-335m-series-d-to-improve-supplychain-resilience-for-global-retailers/', 'Strong robotics product-market fit in logistics, global retailer deployments, industrial credibility.', 4, 'hardware_industrial', 5, 'medium-high', 'Industrial robotics', 'https://presse.bpifrance.fr/exotec-leve-335-millions-de-dollars-et-devient-la-premiere-licorne-industrielle-francaise', 'Strong robotics product-market fit in logistics, global retailer deployments, industrial credibility.', 'Deployment/service intensity; supply chain and capex constraints.'),
  ('Bright Machines', 'USA', 'Industrial automation', 'AI-driven manufacturing automation', 'AI-driven manufacturing automation', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'high', 'https://www.reuters.com/technology/artificial-intelligence/ai-focused-manufacturing-startup-raises-106-million-nvidia-others-2024-06-25/', 'AI server manufacturing demand, modular automation, strategic investors Nvidia/Microsoft/Jabil.', 3, 'hardware_industrial', 4, 'medium-high', 'Industrial automation', 'https://www.brightmachines.com/', 'AI server manufacturing demand, modular automation, strategic investors Nvidia/Microsoft/Jabil.', 'Automation sales cycles; cyclical electronics manufacturing demand.'),
  ('Formlabs', 'USA', 'Additive manufacturing', 'desktop/professional 3D printing', 'desktop/professional 3D printing', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'high', 'https://formlabs.com/company/press/formlabs-raises-series-e-funding-led-by-softbank-vision-fund-2/', 'Accessible professional 3D printing, consumables/materials ecosystem, design/manufacturing adoption.', 4, 'hardware_industrial', 5, 'medium', 'Additive manufacturing', 'https://formlabs.com/blog/2021-review-top-ten-moments/', 'Accessible professional 3D printing, consumables/materials ecosystem, design/manufacturing adoption.', 'Hardware margins, channel distribution, industrial adoption cycles.'),
  ('Desktop Metal', 'USA', 'Additive manufacturing', 'metal 3D printing', 'metal 3D printing', null, 'fail_weak_exit', 'public/SPAC; underperformed', 'NorthAmerica', null, null, 'high', 'https://www.reuters.com/article/business/desktop-metal-to-go-public-through-blank-check-company-at-25-billion-valuation-idUSKBN25M1CH/', 'Large industrial narrative around metal additive manufacturing, strategic investors, SPAC capital access.', 3, 'hardware_industrial', 4, 'high', 'Additive manufacturing', 'https://www.desktopmetal.com/uploads/FINAL-Desktop-Metal-Release.pdf', 'Large industrial narrative around metal additive manufacturing, strategic investors, SPAC capital access.', 'Industrial hardware hype + SPAC valuation risk; public market drawdown lesson.'),
  ('Markforged', 'USA', 'Additive manufacturing', 'composite/metal 3D printing', 'composite/metal 3D printing', null, 'medium', 'public/SPAC; mixed', 'NorthAmerica', null, null, 'high', 'https://www.businesswire.com/news/home/20210224005529/en/Markforged-Leader-in-Additive-Manufacturing-to-Become-Publicly-Listed-Through-Merger-With-one', 'Integrated additive platform, industrial use cases, strong 2021 public market appetite.', 3, 'hardware_industrial', 4, 'medium-high', 'Additive manufacturing', 'https://markforged.com/resources/news-events/markforged-announces-listing-on-new-york-stock-exchange', 'Integrated additive platform, industrial use cases, strong 2021 public market appetite.', 'Valuation compression and manufacturing adoption slower than market hype.'),
  ('Velo3D', 'USA', 'Additive manufacturing', 'metal additive manufacturing for aerospace/energy', 'metal additive manufacturing for aerospace/energy', null, 'fail_uncertain', 'public/SPAC; difficult', 'NorthAmerica', null, null, 'high', 'https://www.businesswire.com/news/home/20210323005467/en/VELO3D-a-Leader-in-the-Rapidly-Growing-High-Value-Metal-Additive-Manufacturing-Market-to-Become-Public-Company', 'Premium industrial metal printing use cases, aerospace/SpaceX adjacency, public capital.', 3, 'hardware_industrial', 4, 'high', 'Additive manufacturing', 'https://ir.velo3d.com/news-events/press-releases/detail/51/velo3d-completes-merger-with-jaws-spitfire-acquisition', 'Premium industrial metal printing use cases, aerospace/SpaceX adjacency, public capital.', 'Specialized hardware scaling, high burn, customer concentration.'),
  ('Rivian', 'USA', 'EV / Automotive', 'electric trucks/SUVs/commercial vans', 'electric trucks/SUVs/commercial vans', null, 'volatile_private', 'IPO; volatile public outcome', 'NorthAmerica', null, null, 'high', 'https://www.sec.gov/Archives/edgar/data/1874178/000119312521289903/d157488ds1.htm', 'Product differentiation, Amazon/Ford backing, EV market timing, brand and fleet opportunity.', 4, 'hardware_industrial', 5, 'very high', 'EV / Automotive', 'https://www.iposcoop.com/ipo/rivian-automotive-inc/', 'Product differentiation, Amazon/Ford backing, EV market timing, brand and fleet opportunity.', 'Auto manufacturing capital intensity; margins and scale execution dominate.'),
  ('Lucid Motors', 'USA', 'EV / Automotive', 'premium electric vehicles', 'premium electric vehicles', null, 'medium', 'SPAC/public; mixed', 'NorthAmerica', null, null, 'high', 'https://ir.lucidmotors.com/news-releases/news-release-details/lucid-motors-go-public-merger-churchill-capital-corp-iv/', 'Premium EV technology/battery range narrative, SPAC capital, Saudi PIF support.', 3, 'hardware_industrial', 4, 'very high', 'EV / Automotive', 'https://www.sec.gov/Archives/edgar/data/1811210/000110465921039318/tm219359-1_s4.htm', 'Premium EV technology/battery range narrative, SPAC capital, Saudi PIF support.', 'Luxury EV demand, manufacturing ramp, valuation risk.'),
  ('Arrival', 'UK', 'EV / Commercial vehicles', 'electric vans/buses microfactories', 'electric vans/buses microfactories', null, 'fail', 'failure / administration', 'Europe', null, null, 'medium-high', 'https://www.theguardian.com/business/2024/feb/05/van-risk', 'Initial pitch: microfactory model, EV delivery demand, major public-market hype.', 3, 'hardware_industrial', 4, 'very high', 'EV / Commercial vehicles', 'https://www.reuters.com/business/aerospace-defense/german-air-taxi-maker-lilium-file-insolvency-2024-11-04/', 'Initial pitch: microfactory model, EV delivery demand, major public-market hype.', 'Manufacturing novelty and undercapitalized execution can destroy SPAC-era valuations.'),
  ('Proterra', 'USA', 'EV / Buses & batteries', 'electric buses and battery systems', 'electric buses and battery systems', null, 'fail', 'Chapter 11 / distressed', 'NorthAmerica', null, null, 'high', 'https://www.reuters.com/business/autos-transportation/ev-firm-proterra-files-chapter-11-bankruptcy-2023-08-07/', 'Public sector electrification demand; battery/bus vertical integration narrative.', 3, 'hardware_industrial', 4, 'very high', 'EV / Buses & batteries', 'https://www.reuters.com/technology/us-ev-startups-under-spotlight-nikola-files-bankruptcy-2025-02-19/', 'Public sector electrification demand; battery/bus vertical integration narrative.', 'Supply chain, demand timing, capital needs and unit economics overwhelmed promise.'),
  ('Fisker', 'USA', 'EV / Automotive', 'electric vehicles', 'electric vehicles', null, 'fail', 'bankruptcy / failure', 'NorthAmerica', null, null, 'medium-high', 'https://www.wsj.com/livecoverage/stock-market-today-dow-sp500-nasdaq-live-06-18-2024/card/now-bankrupt-fisker-raised-money-with-record-growth-projections-that-never-materialized-CH4Nes0MABVeKT14oYeK', 'Asset-light EV narrative and founder brand created early investor appetite.', 3, 'hardware_industrial', 4, 'very high', 'EV / Automotive', 'https://www.reuters.com/technology/us-ev-startups-under-spotlight-nikola-files-bankruptcy-2025-02-19/', 'Asset-light EV narrative and founder brand created early investor appetite.', 'Demand, quality, service and financing risks in asset-light auto models.'),
  ('Joby Aviation', 'USA', 'eVTOL / Aviation mobility', 'electric air taxi', 'electric air taxi', null, 'active', 'public; pre-commercial scale', 'NorthAmerica', null, null, 'high', 'https://ir.jobyaviation.com/news-events/press-releases/detail/16/joby-aviation-announces-closing-of-business-combination', 'Early technical lead, Toyota/Uber relationships, certification path and public capital.', 3, 'hardware_industrial', 4, 'very high', 'eVTOL / Aviation mobility', 'https://www.reuters.com/technology/air-taxi-startup-joby-go-public-66-billion-blank-check-deal-2021-02-24/', 'Early technical lead, Toyota/Uber relationships, certification path and public capital.', 'Certification, safety, infrastructure and capex are gating factors.'),
  ('Archer Aviation', 'USA', 'eVTOL / Aviation mobility', 'electric air taxi', 'electric air taxi', null, 'active', 'public; pre-commercial scale', 'NorthAmerica', null, null, 'high', 'https://investors.archer.com/news/news-details/2021/Archer-A-Leading-Urban-Air-Mobility-Company-To-List-On-NYSE-Through-Merger-With-Atlas-Crest-Investment-Corp/default.aspx', 'Strategic airline partnership, urban air mobility narrative, public-market financing.', 3, 'hardware_industrial', 4, 'very high', 'eVTOL / Aviation mobility', 'https://techcrunch.com/2021/02/10/archer-lands-1-1b-order-from-united-airlines-and-a-spac-deal/', 'Strategic airline partnership, urban air mobility narrative, public-market financing.', 'Orders may be conditional; certification and production milestones matter more than LOIs.'),
  ('Lilium', 'Germany', 'eVTOL / Aviation mobility', 'electric regional air taxi', 'electric regional air taxi', null, 'fail', 'insolvency / failure', 'Europe', null, null, 'high', 'https://www.reuters.com/business/aerospace-defense/german-air-taxi-maker-liliums-units-file-insolvency-shares-plunge-2024-10-24/', 'Compelling regional air mobility concept and SPAC-era capital access.', 3, 'hardware_industrial', 4, 'very high', 'eVTOL / Aviation mobility', 'https://www.reuters.com/business/aerospace-defense/german-air-taxi-maker-lilium-file-insolvency-2024-11-04/', 'Compelling regional air mobility concept and SPAC-era capital access.', 'Battery/certification/funding gaps can kill aviation hardware before commercial launch.'),
  ('Nuro', 'USA', 'Autonomous mobility', 'autonomous delivery / autonomous driving stack', 'autonomous delivery / autonomous driving stack', null, 'active', 'private; pivoted/licensing focus', 'NorthAmerica', null, null, 'high', 'https://www.nuro.ai/blog/nuro-announces-series-e-financing-at-6b-valuation-backed-by-leading-financial-and-strategic-investors', 'Autonomous driving IP, delivery use case, later licensing pivot with strategic partners.', 3, 'hardware_industrial', 4, 'high', 'Autonomous mobility', 'https://www.reuters.com/business/autos-transportation/self-driving-vehicle-startup-nuro-valued-6-billion-late-stage-funding-round-2025-08-21/', 'Autonomous driving IP, delivery use case, later licensing pivot with strategic partners.', 'Robotics fleet economics; valuation downshift from prior peak; pivot quality matters.'),
  ('Aurora Innovation', 'USA', 'Autonomous trucking', 'self-driving trucks', 'self-driving trucks', null, 'active', 'public; commercialization pending', 'NorthAmerica', null, null, 'medium-high', 'https://ir.aurora.tech/sec-filings/all-sec-filings/content/0001193125-21-296332/0001193125-21-296332.pdf', 'Strong technical team, OEM/logistics partnerships, autonomous trucking focus.', 3, 'hardware_industrial', 4, 'high', 'Autonomous trucking', 'https://forgeglobal.com/aurora-innovation_ipo/', 'Strong technical team, OEM/logistics partnerships, autonomous trucking focus.', 'Delayed commercialization and safety/regulatory risk; public-market patience required.'),
  ('Form Energy', 'USA', 'Energy storage', 'long-duration iron-air batteries', 'long-duration iron-air batteries', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'high', 'https://formenergy.com/form-energy-secures-405m-in-series-f-financing-to-expand-iron-air-battery-business-and-operations/', 'Long-duration storage need, differentiated chemistry, grid-scale market pull, strong climate investors.', 4, 'hardware_industrial', 5, 'high', 'Energy storage', 'https://www.canarymedia.com/articles/long-duration-energy-storage/form-energy-raises-405m-for-its-100-hour-iron-air-batteries', 'Long-duration storage need, differentiated chemistry, grid-scale market pull, strong climate investors.', 'Manufacturing scale, utility sales cycles, bankability of new chemistry.'),
  ('Redwood Materials', 'USA', 'Battery recycling / materials', 'battery recycling and critical materials', 'battery recycling and critical materials', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'high', 'https://www.redwoodmaterials.com/news/redwood-announces-350-million-series-e-funding/', 'Battery supply chain localization, recycling/cathode material integration, strategic climate/industrial investors.', 4, 'infrastructure_physical', 5, 'high', 'Battery recycling / materials', 'https://www.redwoodmaterials.com/news/redwood-materials-announces-final-close-of-425m-series-e/', 'Battery supply chain localization, recycling/cathode material integration, strategic climate/industrial investors.', 'Commodity exposure, plant execution, customer contracting.'),
  ('Northvolt', 'Sweden', 'Battery manufacturing', 'lithium-ion battery gigafactory', 'lithium-ion battery gigafactory', null, 'fail', 'bankruptcy / restructuring', 'Europe', null, null, 'high', 'https://www.reuters.com/technology/northvolt-files-chapter-11-bankruptcy-us-2024-11-21/', 'Europe battery sovereignty narrative, strategic automaker backers, huge demand expectation.', 4, 'infrastructure_physical', 5, 'very high', 'Battery manufacturing', 'https://www.reuters.com/technology/northvolt-goes-europe-battery-promise-crisis-2024-11-21/', 'Europe battery sovereignty narrative, strategic automaker backers, huge demand expectation.', 'Gigafactory ramp risk, overexpansion, quality/yield, working capital; crucial negative control.'),
  ('Commonwealth Fusion Systems', 'USA', 'Fusion energy', 'tokamak fusion / magnets', 'tokamak fusion / magnets', null, 'active', 'private deeptech scale-up', 'NorthAmerica', null, null, 'high', 'https://cfs.energy/news-and-media/commonwealth-fusion-systems-closes-1-8-billion-series-b-round/', 'MIT spinout, credible technical roadmap, strategic capital, fusion breakthrough narrative.', 4, 'deep_tech_research', 5, 'very high', 'Fusion energy', 'https://cfs.energy/news-and-media/commonwealth-fusion-systems-raises-863-million-series-b2-round-to-accelerate-the-commercialization-of-fusion-energy/', 'MIT spinout, credible technical roadmap, strategic capital, fusion breakthrough narrative.', 'Scientific and engineering milestones, capital intensity, long time-to-revenue.'),
  ('Helion Energy', 'USA', 'Fusion energy', 'fusion power generation', 'fusion power generation', null, 'active', 'private deeptech scale-up', 'NorthAmerica', null, null, 'high', 'https://www.helionenergy.com/articles/announcing-500-million-fundraise/', 'Bold fusion timeline, prominent backers, differentiated direct electricity capture approach, Microsoft/Nucor commitments reported.', 4, 'deep_tech_research', 5, 'very high', 'Fusion energy', 'https://www.reuters.com/business/energy/helion-raises-425-mln-softbanks-venture-arm-hits-54-bln-valuation-2025-01-28/', 'Bold fusion timeline, prominent backers, differentiated direct electricity capture approach, Microsoft/Nucor commitments reported.', 'Fusion delivery risk; milestone-linked financing; long technical uncertainty.'),
  ('Climeworks', 'Switzerland', 'Carbon removal', 'direct air capture', 'direct air capture', null, 'active', 'private scale-up', 'Europe', null, null, 'high', 'https://climeworks.com/news/equity-fundraising', 'First-mover DAC brand, corporate carbon removal offtake demand, policy/market tailwind.', 3, 'deep_tech_research', 4, 'high', 'Carbon removal', 'https://climeworks.com/news/2022-year-in-review', 'First-mover DAC brand, corporate carbon removal offtake demand, policy/market tailwind.', 'Energy intensity, cost curve, offtake durability.'),
  ('Electric Hydrogen', 'USA', 'Hydrogen / Industrial decarbonization', 'large-scale electrolyzers', 'large-scale electrolyzers', null, 'success_private', 'private unicorn', 'NorthAmerica', null, null, 'high', 'https://eh2.com/electric-hydrogen-raises-380-million-to-transform-the-economics-of-green-hydrogen-production/', 'Electrolyzer cost-down thesis, strategic customers/investors, green hydrogen decarbonization demand.', 4, 'infrastructure_physical', 5, 'high', 'Hydrogen / Industrial decarbonization', 'https://www.reuters.com/sustainability/climate-energy/electric-hydrogen-raises-380-mln-latest-funding-round-2023-10-03/', 'Electrolyzer cost-down thesis, strategic customers/investors, green hydrogen decarbonization demand.', 'Hydrogen economics, project delays, subsidy dependence.'),
  ('Twelve', 'USA', 'Carbon transformation / SAF', 'CO2-to-fuels/materials', 'CO2-to-fuels/materials', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'medium-high', 'https://www.twelve.co/post/building-a-world-made-from-air-twelve-secures-83-million-in-additional-series-c-project-funding', 'Clear aviation fuel pain point, carbon utilization technology, project financing mix.', 3, 'deep_tech_research', 4, 'high', 'Carbon transformation / SAF', 'https://www.esgtoday.com/twelve-raises-83-million-to-transform-captured-co2-into-clean-fuels/', 'Clear aviation fuel pain point, carbon utilization technology, project financing mix.', 'Industrial scale-up, energy costs, offtake economics.'),
  ('Carbon Clean', 'UK', 'Carbon capture', 'modular carbon capture for industry', 'modular carbon capture for industry', null, 'active', 'private scale-up', 'Europe', null, null, 'high', 'https://www.carbonclean.com/en/press-releases/raises-150m-in-record-carbon-capture-funding-round', 'Industrial emissions problem, strategic investors, modular capture product CycloneCC.', 3, 'deep_tech_research', 4, 'medium-high', 'Carbon capture', 'https://www.carbonclean.com/about-us/our-journey', 'Industrial emissions problem, strategic investors, modular capture product CycloneCC.', 'Carbon price/regulation dependence, integration into heavy industry.'),
  ('Stegra / H2 Green Steel', 'Sweden', 'Green steel', 'hydrogen-based steelmaking', 'hydrogen-based steelmaking', null, 'active', 'private infrastructure-scale', 'Europe', null, null, 'high', 'https://www.prnewswire.com/news-releases/h2-green-steel-raises-more-than-4-billion-in-debt-financing-for-the-worlds-first-large-scale-green-steel-plant-302040563.html', 'Hard-to-abate sector, low-carbon steel demand, strategic project finance and offtake narrative.', 3, 'infrastructure_physical', 4, 'very high', 'Green steel', 'https://www.reuters.com/sustainability/climate-energy/swedish-green-steel-firm-stegra-seeks-another-11-billion-financing-2025-10-13/', 'Hard-to-abate sector, low-carbon steel demand, strategic project finance and offtake narrative.', 'Project finance risk, cost overruns, hydrogen economics, state support dependency.'),
  ('Pasqal', 'France', 'Quantum computing', 'neutral atoms quantum computing', 'neutral atoms quantum computing', null, 'active', 'private scale-up', 'Europe', null, null, 'high', 'https://www.pasqal.com/newsroom/pasqal-raises-e100-million-series-b-funding-to-advance-neutral-atoms-quantum-computing/', 'Neutral atom platform, strong French/European quantum ecosystem, sovereign deeptech support.', 4, 'deep_tech_research', 5, 'high', 'Quantum computing', 'https://qt.eu/news/2023/2023-01-25_pasqal-raises-e100m-in-series-b-funding-round', 'Neutral atom platform, strong French/European quantum ecosystem, sovereign deeptech support.', 'Pre-commercial technology; milestones must be technical not narrative-only.'),
  ('Alice & Bob', 'France', 'Quantum computing', 'cat qubits / fault-tolerant quantum', 'cat qubits / fault-tolerant quantum', null, 'active', 'private scale-up', 'Europe', null, null, 'high', 'https://alice-bob.com/newsroom/alice-bob-100m-series-b-fundraising-press-release/', 'Clear differentiated qubit architecture, strong technical founder story, France 2030/deeptech ecosystem.', 4, 'deep_tech_research', 5, 'high', 'Quantum computing', 'https://www.polytechnique.edu/en/news/alice-bob-raises-eu100-million-its-quantum-computer', 'Clear differentiated qubit architecture, strong technical founder story, France 2030/deeptech ecosystem.', 'Long time-to-product; technical milestones and talent density critical.'),
  ('QuEra Computing', 'USA', 'Quantum computing', 'neutral atoms quantum computers', 'neutral atoms quantum computers', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'high', 'https://www.quera.com/press-releases/quera-computing-completes-230m-financing-to-accelerate-development-of-large-scale-fault-tolerant-quantum-computers', 'Neutral-atom scalability thesis, Google/SoftBank/NVentures backing, industrial deployment roadmap.', 4, 'deep_tech_research', 5, 'high', 'Quantum computing', 'https://www.reuters.com/technology/quantum-computing-startup-quera-closes-230-million-funding-round-2025-02-11/', 'Neutral-atom scalability thesis, Google/SoftBank/NVentures backing, industrial deployment roadmap.', 'Fault-tolerance delivery and hardware supply-chain execution.'),
  ('Riverlane', 'UK', 'Quantum software / infrastructure', 'quantum error correction', 'quantum error correction', null, 'active', 'private scale-up', 'Europe', null, null, 'high', 'https://www.riverlane.com/press-release/riverlane-raises-75-million-to-meet-surging-global-demand-for-quantum-error-correction-technology', 'Picks-and-shovels layer for quantum: error correction needed across hardware platforms.', 4, 'deep_tech_research', 5, 'medium', 'Quantum software / infrastructure', 'https://thequantuminsider.com/2024/08/06/riverlane-raises-75-million-in-series-c-round-to-meet-demand-for-quantum-error-correction-technology/', 'Picks-and-shovels layer for quantum: error correction needed across hardware platforms.', 'Commercial timing tied to hardware ecosystem maturity.'),
  ('Quantum Machines', 'Israel', 'Quantum infrastructure', 'quantum control systems', 'quantum control systems', null, 'active', 'private scale-up', 'Asia', null, null, 'medium-high', 'https://www.quantum-machines.co/blog/quantum-machines-2022-review-pushing-quantum-computing-to-new-heights/', 'Infrastructure/control layer sells to multiple quantum labs, less binary than single-machine bet.', 4, 'deep_tech_research', 5, 'medium', 'Quantum infrastructure', 'https://www.quantum-machines.co/blog/quantum-machines-raises-50-million/', 'Infrastructure/control layer sells to multiple quantum labs, less binary than single-machine bet.', 'Market timing and customer budget dependence; hardware platform fragmentation.'),
  ('Quantinuum', 'UK / USA', 'Quantum computing', 'full-stack quantum computing', 'full-stack quantum computing', null, 'active', 'private / corporate-backed', 'Europe', null, null, 'high', 'https://www.honeywell.com/us/en/press/2024/01/honeywell-announces-the-closing-of-300-million-equity-investment-round-for-quantinuum-at-5-billion-pre-money-valuation', 'Corporate spinout/backing from Honeywell, full-stack capabilities, enterprise quantum partnerships.', 3, 'deep_tech_research', 4, 'high', 'Quantum computing', 'https://www.quantinuum.com/press-releases/honeywell-announces-600-million-capital-raise-for-quantinuum-at-10b-pre-money-equity-valuation-to-advance-quantum-computing-at-scale', 'Corporate spinout/backing from Honeywell, full-stack capabilities, enterprise quantum partnerships.', 'Not pure startup; compare separately due corporate parent/ownership structure.'),
  ('IonQ', 'USA', 'Quantum computing', 'trapped-ion quantum computers', 'trapped-ion quantum computers', null, 'active', 'public/SPAC', 'NorthAmerica', null, null, 'high', 'https://www.ionq.com/news/october-01-2021-ionq-listed-on-nyse', 'First pure-play public quantum listing, cloud access partnerships, trapped-ion differentiation.', 3, 'deep_tech_research', 4, 'high', 'Quantum computing', 'https://www.reuters.com/technology/quantum-computing-provider-ionq-go-public-via-2-bln-spac-deal-2021-03-08/', 'First pure-play public quantum listing, cloud access partnerships, trapped-ion differentiation.', 'Public quantum volatility; revenue far behind valuation expectations at time of listing.'),
  ('Rigetti Computing', 'USA', 'Quantum computing', 'superconducting quantum computing', 'superconducting quantum computing', null, 'volatile_private', 'public/SPAC; volatile', 'NorthAmerica', null, null, 'medium', 'https://investors.rigetti.com/', 'Full-stack superconducting platform and quantum cloud positioning.', 3, 'deep_tech_research', 4, 'high', 'Quantum computing', 'https://www.sec.gov/edgar/browse/?CIK=1838359', 'Full-stack superconducting platform and quantum cloud positioning.', 'Public quantum hype, funding needs, and technical milestones must be tracked rigorously.'),
  ('D-Wave Quantum', 'Canada', 'Quantum computing', 'quantum annealing / gate model', 'quantum annealing / gate model', null, 'active', 'public; long-cycle commercialization', 'NorthAmerica', null, null, 'medium-high', 'https://www.dwavesys.com/company/newsroom/press-release/d-wave-quantum-inc-completes-business-combination-with-dpcm-capital-inc/', 'Long-standing quantum brand, early enterprise quantum annealing customers.', 3, 'deep_tech_research', 3, 'high', 'Quantum computing', 'https://www.sec.gov/edgar/browse/?CIK=1907982', 'Long-standing quantum brand, early enterprise quantum annealing customers.', 'Long technical cycles and monetization gap; not a clean VC startup comparator.'),
  ('PsiQuantum', 'USA / UK origins', 'Quantum computing', 'photonic quantum computing', 'photonic quantum computing', null, 'active', 'private deeptech scale-up', 'Europe', null, null, 'medium', 'https://www.psiquantum.com/', 'Ambitious photonic architecture, large-scale fault-tolerant thesis, major investor appetite.', 4, 'deep_tech_research', 5, 'very high', 'Quantum computing', 'https://en.wikipedia.org/wiki/PsiQuantum', 'Ambitious photonic architecture, large-scale fault-tolerant thesis, major investor appetite.', 'Very high technical and capital risk; source figures carefully.'),
  ('Verkada', 'USA', 'Cyber-physical security', 'cloud-managed security cameras/access control', 'cloud-managed security cameras/access control', null, 'success_private', 'private unicorn', 'NorthAmerica', null, null, 'medium', 'https://www.verkada.com/newsroom/', 'SaaS-like recurring model wrapped around physical security hardware; enterprise distribution.', 4, 'hardware_industrial', 5, 'medium', 'Cyber-physical security', 'https://www.verkada.com/', 'SaaS-like recurring model wrapped around physical security hardware; enterprise distribution.', 'Security/privacy incidents and hardware supply chain risk.'),
  ('Samsara', 'USA', 'Industrial IoT / fleet software', 'connected operations cloud', 'connected operations cloud', null, 'success', 'IPO / public success', 'NorthAmerica', null, null, 'high', 'https://www.sec.gov/Archives/edgar/data/1642896/000119312521331064/d209117ds1.htm', 'Hardware sensors plus recurring SaaS, fleet/industrial vertical focus, strong go-to-market.', 3, 'software_with_hardware', 4, 'medium', 'Industrial IoT / fleet software', 'https://www.samsara.com/company/news', 'Hardware sensors plus recurring SaaS, fleet/industrial vertical focus, strong go-to-market.', 'Hardware gross margin and device deployment complexity; public comparables useful.'),
  ('Axonius', 'Israel / USA', 'Cybersecurity', 'cyber asset management', 'cyber asset management', null, 'active', 'private scale-up', 'Asia', null, null, 'medium', 'https://www.axonius.com/company/newsroom', 'Clear pain around asset visibility, fast enterprise adoption, low capex software model.', 3, 'software_pure', 4, 'low', 'Cybersecurity', 'https://www.axonius.com/', 'Clear pain around asset visibility, fast enterprise adoption, low capex software model.', 'Crowded cybersecurity category; need ARR/retention proof.'),
  ('Claroty', 'Israel / USA', 'Cybersecurity / industrial', 'OT/IoT/industrial cybersecurity', 'OT/IoT/industrial cybersecurity', null, 'active', 'private scale-up', 'Asia', null, null, 'medium', 'https://claroty.com/news', 'Industrial/critical-infrastructure cyber need, OT visibility, strategic investor/customer relevance.', 4, 'software_with_hardware', 5, 'low-medium', 'Cybersecurity / industrial', 'https://claroty.com/', 'Industrial/critical-infrastructure cyber need, OT visibility, strategic investor/customer relevance.', 'Long enterprise/industrial sales cycles; integration into legacy environments.'),
  ('Dragos', 'USA', 'Cybersecurity / industrial', 'industrial control systems security', 'industrial control systems security', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'medium', 'https://www.dragos.com/news/', 'Deep ICS expertise, government/critical infrastructure tailwind, strong category specialization.', 4, 'software_with_hardware', 5, 'low-medium', 'Cybersecurity / industrial', 'https://www.dragos.com/', 'Deep ICS expertise, government/critical infrastructure tailwind, strong category specialization.', 'Services-heavy elements can dilute software multiples; buyer education required.'),
  ('Armis', 'Israel / USA', 'Cybersecurity / IoT', 'asset visibility and exposure management', 'asset visibility and exposure management', null, 'active', 'private scale-up / PE-backed', 'Asia', null, null, 'medium', 'https://www.armis.com/newsroom/', 'Agentless device visibility, IoT/OT explosion, broad enterprise need.', 4, 'software_pure', 5, 'low', 'Cybersecurity / IoT', 'https://www.armis.com/', 'Agentless device visibility, IoT/OT explosion, broad enterprise need.', 'Competitive convergence in exposure management; acquisition/PE ownership changes affect comparability.');

-- 6. Ajouts personnels - 12 boites manquantes (quantum, batteries,
--    aerospace, additive manufacturing, robotics humanoide)
insert into public.historical_companies
  (name, country, sector, sub_sector, subsector, founded, outcome, exit_type,
   region, eu_status, state_influence_tag, data_quality, primary_source_url,
   analyst_note, confidence_score,
   asset_class, vc_relevance_score, capital_intensity, vertical_v4,
   source_2, what_made_it_work, key_risks_lessons)
values
  ('Atom Computing', 'United States', 'Quantum computing', 'Neutral atom quantum', 'Neutral atom quantum', null, 'active', 'private deeptech scale-up', 'NorthAmerica', null, null, 'Medium', 'https://atom-computing.com', 'Neutral atom approach scalable to 1000+ qubits achieved 2023; Microsoft Azure partnership', 3, 'deep_tech_research', 4, 'high', 'Quantum computing', 'https://news.microsoft.com', 'Neutral atom approach scalable to 1000+ qubits achieved 2023; Microsoft Azure partnership', 'Long road to fault-tolerance; intense competition with IBM, Google, Pasqal, IonQ'),
  ('PsiQuantum', 'United States', 'Quantum computing', 'Photonic quantum', 'Photonic quantum', null, 'active', 'private deeptech scale-up', 'NorthAmerica', null, null, 'Medium', 'https://psiquantum.com', 'Bet on silicon photonics manufacturable in existing fabs; partnership GlobalFoundries; AU and US gov funding (Brisbane and Chicago)', 3, 'deep_tech_research', 4, 'very high', 'Quantum computing', 'https://www.globalfoundries.com', 'Bet on silicon photonics manufacturable in existing fabs; partnership GlobalFoundries; AU and US gov funding (Brisbane and Chicago)', 'Photonic approach unproven at fault-tolerant scale; massive cash burn; binary outcome'),
  ('Sila Nanotechnologies', 'United States', 'Battery materials', 'Silicon anode', 'Silicon anode', null, 'active', 'private deeptech scale-up', 'NorthAmerica', null, null, 'Medium', 'https://silanano.com', 'Mercedes-Benz partnership for EQG; Whoop wearable launch validated chemistry; Washington state factory operational', 3, 'infrastructure_physical', 4, 'very high', 'Battery materials', 'https://group.mercedes-benz.com', 'Mercedes-Benz partnership for EQG; Whoop wearable launch validated chemistry; Washington state factory operational', 'Silicon anode chemistry capex enormous; competition from QuantumScape/Solid Power; demand cycle EV'),
  ('QuantumScape', 'United States', 'Battery materials', 'Solid-state battery', 'Solid-state battery', null, 'fail_weak_exit', 'public/SPAC; underperformed', 'NorthAmerica', null, null, 'High', 'https://www.quantumscape.com', 'VW partnership; ceramic separator technology genuine IP; Bill Gates and Khosla early backers', 4, 'infrastructure_physical', 3, 'very high', 'Battery materials', 'https://investors.quantumscape.com', 'VW partnership; ceramic separator technology genuine IP; Bill Gates and Khosla early backers', 'Multi-decade commercialization timeline; cell shipped years late; SPAC hype unsustained'),
  ('Boom Supersonic', 'United States', 'eVTOL / Aviation mobility', 'Supersonic commercial aircraft', 'Supersonic commercial aircraft', null, 'active', 'private deeptech scale-up', 'NorthAmerica', null, null, 'Medium', 'https://boomsupersonic.com', 'XB-1 demonstrator broke sound barrier 2025; Symphony engine in-house development after RR exit', 3, 'hardware_industrial', 3, 'very high', 'eVTOL / Aviation mobility', 'https://www.flightglobal.com', 'XB-1 demonstrator broke sound barrier 2025; Symphony engine in-house development after RR exit', 'Engine partner pulled out (Rolls-Royce); certification for supersonic commercial flight unprecedented; binary'),
  ('Relativity Space', 'United States', 'eVTOL / Aviation mobility', '3D printed rocket', '3D printed rocket', null, 'active', 'private; pivoted/licensing focus', 'NorthAmerica', null, null, 'Medium', 'https://www.relativityspace.com', 'Largest metal 3D printer (Stargate); Terran 1 reached space 2023; pivoted to larger Terran R', 3, 'hardware_industrial', 3, 'very high', 'eVTOL / Aviation mobility', 'https://techcrunch.com', 'Largest metal 3D printer (Stargate); Terran 1 reached space 2023; pivoted to larger Terran R', 'Pivot Terran 1 to Terran R signals economics issue; intense competition SpaceX/Rocket Lab; capital starvation risk'),
  ('Sierra Space', 'United States', 'eVTOL / Aviation mobility', 'Spaceplane / orbital', 'Spaceplane / orbital', null, 'active', 'private deeptech scale-up', 'NorthAmerica', null, null, 'Medium', 'https://www.sierraspace.com', 'Dream Chaser spaceplane NASA contracts; Orbital Reef (Blue Origin partnership) commercial space station', 3, 'hardware_industrial', 3, 'very high', 'eVTOL / Aviation mobility', 'https://www.nasa.gov', 'Dream Chaser spaceplane NASA contracts; Orbital Reef (Blue Origin partnership) commercial space station', 'Capex scaling; dependence on government contracts; commercial timeline beyond 2027'),
  ('Carbon Inc.', 'United States', 'Additive manufacturing', 'Digital Light Synthesis', 'Digital Light Synthesis', null, 'active', 'private; pivoted/licensing focus', 'NorthAmerica', null, null, 'Medium', 'https://www.carbon3d.com', 'Adidas Futurecraft 4D shoe partnership; subscription printer model; deep dental and medical verticals', 3, 'hardware_industrial', 3, 'medium-high', 'Additive manufacturing', 'https://www.adidas.com', 'Adidas Futurecraft 4D shoe partnership; subscription printer model; deep dental and medical verticals', 'Adidas partnership volume below expectations; broader 3D printing softness 2022-2024; price compression'),
  ('Apptronik', 'United States', 'Robotics / Humanoid', 'Humanoid robotics industrial', 'Humanoid robotics industrial', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'Medium', 'https://apptronik.com', 'Apollo robot pilot Mercedes-Benz; NASA Valkyrie heritage; B2B industrial focus from start', 3, 'hardware_industrial', 4, 'high', 'Robotics / Humanoid', 'https://www.bloomberg.com', 'Apollo robot pilot Mercedes-Benz; NASA Valkyrie heritage; B2B industrial focus from start', 'Crowded space (Figure, 1X, Tesla Optimus, Agility); manufacturing scaling; pricing pressure'),
  ('1X Technologies', 'Norway', 'Robotics / Humanoid', 'Humanoid robotics consumer/industrial', 'Humanoid robotics consumer/industrial', null, 'active', 'private scale-up', 'Europe', null, null, 'Medium', 'https://www.1x.tech', 'OpenAI partnership for foundation models; NEO consumer humanoid focus; Norway + US', 3, 'hardware_industrial', 4, 'high', 'Robotics / Humanoid', 'https://openai.com', 'OpenAI partnership for foundation models; NEO consumer humanoid focus; Norway + US', 'Consumer humanoid timing speculative; safety in domestic environments unsolved; OpenAI dependence'),
  ('Sanctuary AI', 'Canada', 'Robotics / Humanoid', 'Humanoid general purpose', 'Humanoid general purpose', null, 'active', 'private scale-up', 'NorthAmerica', null, null, 'Medium', 'https://www.sanctuary.ai', 'Phoenix robot deployment Magna; Canadian government strategic investment', 3, 'hardware_industrial', 3, 'high', 'Robotics / Humanoid', 'https://www.canada.ca', 'Phoenix robot deployment Magna; Canadian government strategic investment', 'Smaller capital base than Figure/Apptronik; commercialization slower than peers'),
  ('Symbotic', 'United States', 'Warehouse robotics', 'AI-enabled warehouse automation', 'AI-enabled warehouse automation', null, 'volatile_private', 'IPO; volatile public outcome', 'NorthAmerica', null, null, 'High', 'https://www.symbotic.com', 'Walmart anchor contract massive backlog; SoftBank GreenBox JV;', 4, 'hardware_industrial', 4, 'high', 'Warehouse robotics', 'https://investors.symbotic.com', 'Walmart anchor contract massive backlog; SoftBank GreenBox JV;', 'Walmart concentration risk; backlog includes long-tail commitments; complexity scaling deployment');

-- 7. Mise a jour Pasqal avec chiffres 2026 fournis par operateur
update public.historical_companies set
  outcome = 'success',
  exit_type = 'public/SPAC; commercializing',
  analyst_note = '2026 SPAC merger via Bleichroeder Acquisition Corp II at 2.6B$ pro forma. 200M$ convertible round closed 2026 led by Inflection Point and Bpifrance. CA growth ~100% in 2025. Backlog of 80M$ in firm contracts and grants. Cash position 158M$ Feb 2026. Real industrial customers including CMA CGM, NVIDIA and BMW. Competitive edge: neutral atom approach more stable at room temperature than competing modalities.',
  what_made_it_work = 'Neutral atom modality more stable at room temperature than superconducting approaches. Diversified customer base across logistics (CMA CGM), automotive (BMW) and AI infrastructure (NVIDIA). Successful SPAC at credible valuation 2.6B$ pro forma 2026.',
  key_risks_lessons = 'Quantum advantage proof point still ahead. SPAC volatility post-listing. Competition with Atom Computing, IBM, Google, IonQ on different modalities.',
  data_quality = 'High',
  vc_relevance_score = 5,
  capital_intensity = 'high'
where name = 'Pasqal';

-- 8. Update Form Energy avec chiffres frais
update public.historical_companies set
  analyst_note = 'Series F October 2024 of 405M$ at 3.42B$ valuation. Documented revenues 85.3M$ 2024 marking transition R&D to industrial. Goal 50 GWh per year by 2028 via Iron-Air chemistry. Backers include T. Rowe Price, Bill Gates Breakthrough Energy, GE Vernova. Cost target 10x cheaper than Lithium-ion for grid storage.',
  data_quality = 'High',
  vc_relevance_score = 5
where name = 'Form Energy';

-- 9. Update Figure AI avec chiffres frais
update public.historical_companies set
  analyst_note = 'Late 2025/2026 valuation around 39B$ implied by strategic rounds. Investors include OpenAI, NVIDIA, Jeff Bezos and Microsoft. Figure 03 unveiled 2026. Active pilot deployment with BMW for automotive assembly. Vertical integration AI brain plus hardware body.',
  data_quality = 'High',
  vc_relevance_score = 5
where name = 'Figure AI';

-- 10. Update Joby avec chiffres frais
update public.historical_companies set
  analyst_note = 'Public NYSE. February 2026 raise of 1.2B$. Valuation around 5-6B$ depending on date. Most vertically integrated eVTOL player (cells, motors, software, planned ride network). Heavy dependence on FAA certification timeline and urban infrastructure rollout.',
  data_quality = 'High',
  vc_relevance_score = 5
where name = 'Joby Aviation';

-- 11. Update Alice & Bob avec chiffres frais
update public.historical_companies set
  analyst_note = 'Total Series B funding 138M$ by 2026. New 50M$ lab in 2026 plus NVIDIA CUDA-Q integration partnership. Cat qubit (self-correcting bit) approach theoretically validated and beginning empirical proofs. If scale validation succeeds, could obsolete error-prone competitor machines.',
  data_quality = 'High',
  vc_relevance_score = 5
where name = 'Alice & Bob';

-- 12. Index sur les nouvelles colonnes
create index if not exists idx_historical_asset_class on public.historical_companies (asset_class);
create index if not exists idx_historical_vc_relevance on public.historical_companies (vc_relevance_score);

-- 13. Verification finale
-- select count(*) from public.historical_companies;  -- attendu: ~190
-- select asset_class, count(*) from public.historical_companies group by asset_class order by 2 desc;

